name: guys_on_work
description: "A personal project with the objective to make easier the knowledge of the activities of the partness."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  lottie: ^2.7.0
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#262833"
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#262833"
    theme_color: "#262833"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/animations/
    - assets/music/
    - assets/videos/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter-Black.ttf
          weight: 900

    - family: Sora
      fonts:
        - asset: assets/fonts/sora/Sora-Thin.ttf
          weight: 100
        - asset: assets/fonts/sora/Sora-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/sora/Sora-Light.ttf
          weight: 300
        - asset: assets/fonts/sora/Sora-Regular.ttf
          weight: 400
        - asset: assets/fonts/sora/Sora-Medium.ttf
          weight: 500
        - asset: assets/fonts/sora/Sora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/sora/Sora-Bold.ttf
          weight: 700
        - asset: assets/fonts/sora/Sora-ExtraBold.ttf
          weight: 800
